### PR TITLE
ft-update-ui

### PR DESCRIPTION
**Pull request by Antoh1**
Updated landing-page, bucketlists page and itemsview

### CODE REVIEW

**Comment by Antoh1** [comment]
@GloriahMoses come review this

**Comment by GloriahMoses** [comment]
Awesome job. 
Your landing page needs some work though.

**Comment by GloriahMoses** [comment]
This [link ](https://blog.hubspot.com/marketing/landing-page-examples-list)might be helpful

**Comment by Antoh1** [comment]
Thank you, I have just worked on the landing page, in my next pull request.. cheers

**Pull request merged**
